before_install:
  - gem install cocoapods
  - pod repo update --project-directory=DoMemory
install:
  - brew update
  - pod install --project-directory=DoMemory
language: swift
osx_image: xcode12.4
xcode_workspace: DoMemory/DoMemory.xcworkspace
xcode_scheme: DoMemory
xcode_destination: platform=iOS Simulator, OS=14.0, name=iPhone 8
podfile: DoMemory/Podfile
script:
  - xcodebuild workspace -project DoMemory/DoMemory.xcworkspace -scheme DoMemory -destination "platform=iOS Simulator,name=iPhone 8" -sdk iphonesimulator14.0 CODE_SIGNING_REQUIRED=NO
notifications:
  slack: ezequielbrrt:zwQOFPtXkSPTpGF2iP9QFetC
