before_install:
  - gem install cocoapods
install:
  - brew update
  - pod install
language: swift
osx_image: xcode12.4
xcode_workspace: DoMemory/DoMemory.xcworkspace
xcode_scheme: DoMemory
xcode_destination: platform=iOS Simulator, OS=14.0, name=iPhone 8
script:
  - xcodebuild workspace -project DoMemory/DoMemory.xcworkspace -scheme DoMemory -destination "platform=iOS Simulator,name=iPhone 8" -sdk iphonesimulator14.0 CODE_SIGNING_REQUIRED=NO
