#!/usr/bin/env python3
"""Export iPad 12.9" App Store screenshots (2048x2732) from Paper artboards.

Artboard naming convention (same as the phone script):
  "{base_name} — {app_locale}"
  e.g. "01 Flip & Match — en", "02 Play Dozens — de"

The script connects to the Paper MCP server, discovers all matching artboards,
captures them, and saves them to screenshots/ipad-12.9/{asc-locale}/{slug}.jpg.

Output: screenshots/ipad-12.9/{asc-locale}/{slug}.jpg
"""

import json
import os
import shutil
import subprocess
import time
import urllib.request

MCP_URL = "http://127.0.0.1:29979/mcp"
OUT_DIR = os.path.join(os.path.dirname(__file__), "screenshots", "ipad-12.9")

ASC_IPAD_WIDTH  = 2048
ASC_IPAD_HEIGHT = 2732

# Lightweight Paper pages generated by split_ipad_paper_pages.py.
PAGE_IDS = {
    "en": "9-0",
    "de": "A-0",
    "es-419": "B-0",
    "fr": "C-0",
    "hi": "D-0",
    "it": "E-0",
    "ja": "F-0",
    "ko": "G-0",
    "pt-BR": "H-0",
    "zh-Hans": "I-0",
}

# Base artboard name → output filename. An artboard may be either the bare base
# name (English) or localized as "{base_name} — {app_locale}".
SCREEN_SPECS = [
    ("iPad 1 — Hero Gameplay",         "01_hero_gameplay.jpg"),
    ("iPad 2 — Play.Create.Challenge", "02_play_create_challenge.jpg"),
    ("iPad 3 — Multiplayer",           "03_multiplayer.jpg"),
    ("iPad 4 — Play Dozens",           "04_play_dozens.jpg"),
    ("iPad 5 — Create Your Own",       "05_create_your_own.jpg"),
    ("iPad 6 — Choose Challenge",      "06_choose_challenge.jpg"),
    ("iPad 7 — Levels (NEW)",          "07_levels.jpg"),
]

# Maps Paper/app locale codes → App Store Connect locale codes.
LOCALE_MAP = {
    "en":     "en-US",
    "de":     "de-DE",
    "es-419": "es-MX",
    "fr":     "fr-FR",
}


def mcp_call(method, params, req_id):
    """Make a single JSON-RPC call to the Paper MCP server, return parsed result."""
    payload = json.dumps({
        "jsonrpc": "2.0",
        "id": req_id,
        "method": method,
        "params": params,
    }).encode()

    req = urllib.request.Request(
        MCP_URL,
        data=payload,
        headers={
            "Content-Type": "application/json",
            "Accept": "application/json, text/event-stream",
        },
        method="POST",
    )

    with urllib.request.urlopen(req, timeout=30) as resp:
        raw = resp.read().decode()

    for line in raw.splitlines():
        if line.startswith("data: "):
            return json.loads(line[6:])

    raise RuntimeError(f"No data line in SSE response: {raw[:200]}")


def text_payload(result):
    """Decode the first JSON text item in a Paper tool response."""
    if "error" in result:
        raise RuntimeError(f"MCP error: {result['error']}")
    # Paper reports unknown tools and tool failures as isError inside result,
    # not as a JSON-RPC error. Without this check a renamed tool fails silently
    # and the caller happily reads whichever page happened to be open.
    if result.get("result", {}).get("isError"):
        raise RuntimeError(f"Paper tool error: {result['result']['content']}")
    for item in result["result"]["content"]:
        if item.get("type") == "text":
            return json.loads(item["text"])
    raise RuntimeError("Paper returned no text payload")


def current_file_id():
    """Resolve the open Paper file's ID from the URL in get_basic_info."""
    payload = text_payload(mcp_call("tools/call", {"name": "get_basic_info", "arguments": {}}, 1))
    # https://app.paper.design/file/<fileId>/<pageId>
    return payload["url"].split("/file/")[1].split("/")[0]


def open_page(page_id, file_id):
    """Switch the active page. Paper replaced open_page with open_file(pageId)."""
    result = mcp_call("tools/call", {
        "name": "open_file",
        "arguments": {"fileId": file_id, "pageId": page_id},
    }, 1)
    text_payload(result)


def discover_artboards(page_id, file_id):
    """Return [(node_id, filename)] for one locale-specific Paper page."""
    open_page(page_id, file_id)
    result = mcp_call("tools/call", {"name": "get_basic_info", "arguments": {}}, 1)
    payload = text_payload(result)
    if payload["pageId"] != page_id:
        raise RuntimeError(
            f"Expected page {page_id}, but Paper is on {payload['pageId']}"
        )
    artboards_by_name = {a["name"]: a["id"] for a in payload["artboards"]}
    discovered = []
    for base_name, filename in SCREEN_SPECS:
        node_id = artboards_by_name.get(base_name)
        if not node_id:
            raise RuntimeError(f"Missing artboard on Paper page {page_id}: {base_name}")
        discovered.append((node_id, filename))

    return discovered


def export_artboards(artboards, req_id, retries=6, delay=1.5):
    """Batch-export one Paper page and return node ID to generated file path."""
    nodes = {
        node_id: [{"format": "jpg", "scale": f"{ASC_IPAD_WIDTH}w"}]
        for node_id, _ in artboards
    }

    for attempt in range(retries):
        payload = text_payload(mcp_call(
            "tools/call",
            {"name": "export", "arguments": {"type": "image", "nodes": nodes}},
            req_id,
        ))
        exports = {item["nodeId"]: item["filePath"] for item in payload.get("exports", [])}
        if len(exports) == len(artboards):
            return exports
        if attempt < retries - 1:
            time.sleep(delay)

    errors = payload.get("errors", [])
    raise RuntimeError(f"Paper export failed: {errors}")


def main():
    mcp_call(
        "initialize",
        {
            "protocolVersion": "2024-11-05",
            "capabilities": {},
            "clientInfo": {"name": "asc-ipad-export", "version": "1.0"},
        },
        0,
    )

    files_written = []
    total = len(PAGE_IDS) * len(SCREEN_SPECS)
    current = 0
    file_id = current_file_id()

    for app_locale, page_id in PAGE_IDS.items():
        locale = LOCALE_MAP.get(app_locale, app_locale)
        artboards = discover_artboards(page_id, file_id)
        exported = export_artboards(artboards, 100 + current)
        dest_dir = os.path.join(OUT_DIR, locale)
        os.makedirs(dest_dir, exist_ok=True)

        for node_id, filename in artboards:
            current += 1
            dest = os.path.join(dest_dir, filename)
            print(f"[{current:2d}/{total}] {locale}/{filename}", end="  ", flush=True)
            shutil.move(exported[node_id], dest)

            # Enforce exact App Store iPad dimensions.
            subprocess.run(
                ["/usr/bin/sips", "-z", str(ASC_IPAD_HEIGHT), str(ASC_IPAD_WIDTH), dest],
                check=True, capture_output=True,
            )

            result = subprocess.run(
                ["/usr/bin/sips", "-g", "pixelWidth", "-g", "pixelHeight", dest],
                capture_output=True, text=True, check=True,
            )
            dims = {
                line.split(":")[0].strip(): line.split(":")[1].strip()
                for line in result.stdout.splitlines()
                if ":" in line
            }
            w, h = dims.get("pixelWidth", "?"), dims.get("pixelHeight", "?")
            print(f"{w}x{h}")
            files_written.append(dest)

    print(
        f"\n{len(files_written)} iPad screenshots saved to {OUT_DIR} "
        f"({ASC_IPAD_WIDTH}x{ASC_IPAD_HEIGHT})"
    )


if __name__ == "__main__":
    main()
