# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build to release"
  lane :release do
    get_push_certificate
    #sync_code_signing(type: "appstore")
    next_build_number = app_store_build_number + 1
    sh("mise exec tuist@4.195.6 -- tuist install --path .")
    sh("CURRENT_PROJECT_VERSION=#{next_build_number} mise exec tuist@4.195.6 -- tuist generate --path . --no-open")
    build_app(scheme: "DoMemory",
              workspace: "DoMemory.xcworkspace",
              include_bitcode: true)
    upload_to_app_store
   # slack(message: "Successfully uploaded a new App Store build")
  end
end
