# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build to release"
  lane :release do
    get_push_certificate
    #sync_code_signing(type: "appstore")
    build_app(scheme: "DoMemory",
              workspace: "DoMemory.xcworkspace",
              include_bitcode: true)
    increment_build_number(build_number: app_store_build_number + 1,
                            xcodeproj: "DoMemory.xcodeproj")
    upload_to_app_store
   # slack(message: "Successfully uploaded a new App Store build")
  end
end

