# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'DoMemory' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  inhibit_all_warnings!

  # Pods for DoMemory
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'CodableFirebase'
  pod 'WaterfallGrid', '~> 0.4.0'
  pod 'Firebase/Messaging'
  pod 'AppLovinSDK'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
          config.build_settings['ARCHS'] = '$(ARCHS_STANDARD)'
          config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
  end
end