import ProjectDescription

/// Exists solely to turn off Tuist's autogenerated workspace scheme.
///
/// Without this, generation produced a second scheme, `DoMemory-Workspace`, listing every
/// target — including `DoMemoryTests` — with `buildForArchiving = "YES"`. Archiving with
/// that scheme compiled the test target in Release, where `ENABLE_TESTABILITY` is off, so
/// `@testable import DoMemory` failed with:
///
///     DoMemoryTests.swift:9: Unable to resolve Swift module dependency to a compatible
///     module: 'DoMemory' … module built without '-enable-testing'
///
/// Tests have no business in an archive, and the two schemes were indistinguishable in
/// Xcode's scheme menu, so the wrong one was easy to pick. `Project.swift` already defines
/// the correct `DoMemory` scheme — app-only build action, tests run in Debug — and that is
/// now the only one generation emits.
let workspace = Workspace(
    name: "DoMemory",
    projects: ["."],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
